# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 码小虎的博客
description: ''
keywords:
author: 码小虎
language: zh-CN
timezone: 'Asia/Shanghai'
index_img: https://maxiaohu.oss-cn-nanjing.aliyuncs.com/head.png
default_top_img: https://maxiaohu.oss-cn-nanjing.aliyuncs.com/xiangqing.jpg #我设置的本地图片

social:
  fab fa-github: https://github.com/lumia431 || Github
  fab fa-weixin: https://maxiaohu.oss-cn-nanjing.aliyuncs.com/wechat.jpg || WeChat
  fab fa-qq: https://maxiaohu.oss-cn-nanjing.aliyuncs.com/qq.jpg || QQ

cover:
  # 是否显示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面显示的位置
  # 三个值可配置 left , right , both
  position: right
  # 当没有设置cover时，默认的封面显示
  default_cover: https://maxiaohu.oss-cn-nanjing.aliyuncs.com/content.jpg

# Global font settings
# Don't modify the following settings unless you know how they work (非必要不要修改)
# font:
#   global-font-size: "10px"
#   code-font-size: "10px"
#   font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Lato, Roboto, "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei", sans-serif
#   code-font-family: consolas, Menlo, "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei", sans-serif

# # Font settings for the site title and site subtitle
# # 左上角网站名字 主页居中网站名字
# blog_title_font:
#   font_link: https://fonts.googleapis.com/css?family=Titillium+Web&display=swap
#   font-family: Titillium Web, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft JhengHei', 'Microsoft YaHei', sans-serif

wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

# Local search
local_search:
  enable: true

comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use: Waline
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: true # Display comment count in top_img
  card_post_count: true # Display comment count in Home Page

# waline - A simple comment system with backend support fork from Valine
# https://waline.js.org/
waline:
  serverURL: https://voice-wakeup.top
  avatar: monsterid # gravatar style https://zh-tw.gravatar.com/site/implement/images/#default-image
  emojiCDN: # emoji CDN
  bg: # waline background
  visitor: false
  option:


# # Twikoo
# # https://github.com/imaegoo/twikoo
# twikoo:
#   envId: https://my-twikoo-hazel-mu.vercel.app/ 
#   region: 
#   visitor: true
#   option:

chat_btn: true

subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  # loop (循环打字)
  loop: true
  source: false
  # 如果关闭打字效果，subtitle 只会显示 sub 的第一行文字
  sub:
    - 多看书，多看报；少玩电脑，多睡觉


avatar:
  img: https://maxiaohu.oss-cn-nanjing.aliyuncs.com/avatar.jpg #图片路径
  effect: false #头像会一直转圈  

footer:
  owner:
    enable: true
    since: 2022   # 站点起始时间
  custom_text: I wish you to become your own sun, no need to rely on who's light.<p><a target="_blank" href="https://hexo.io/"><img src="https://img.shields.io/badge/Frame-Hexo-blue?style=flat&logo=hexo" title="博客框架为Hexo"></a>&nbsp;<a target="_blank" href="https://butterfly.js.org/"><img src="https://img.shields.io/badge/Theme-Butterfly-6513df?style=flat&logo=bitdefender" title="主题采用butterfly"></a>&nbsp;<a target="_blank" href="https://www.jsdelivr.com/"><img src="https://img.shields.io/badge/CDN-jsDelivr-orange?style=flat&logo=jsDelivr" title="本站使用JsDelivr为静态资源提供CDN加速"></a> &nbsp;<a target="_blank" href="https://vercel.com/ "><img src="https://img.shields.io/badge/Hosted-Vervel-brightgreen?style=flat&logo=Vercel" title="本站采用双线部署，默认线路托管于Vercel"></a>&nbsp;<a target="_blank" href="https://vercel.com/ "><img src="https://img.shields.io/badge/Hosted-Coding-0cedbe?style=flat&logo=Codio" title="本站采用双线部署，联通线路托管于Coding"></a>&nbsp;<a target="_blank" href="https://github.com/"><img src="https://img.shields.io/badge/Source-Github-d021d6?style=flat&logo=GitHub" title="本站项目由Gtihub托管"></a>&nbsp;<a target="_blank" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://img.shields.io/badge/Copyright-BY--NC--SA%204.0-d42328?style=flat&logo=Claris" title="本站采用知识共享署名-非商业性使用-相同方式共享4.0国际许可协议进行许可"></a></p>

footer_bg: true
# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://maxiaohu.top
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly
highlight_theme: light
highlight_copy: true
highlight_shrink: false #代码框不展开，需点击 '>' 打开
code_word_wrap: true

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清单||fa fa-heartbeat:
    音乐: /music/ || fas fa-music
    照片: /Gallery/ || fas fa-images
    电影: /movies/ || fas fa-video
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

# Sponsor/reward
reward:
  enable: true
  QR_code:
     - img: https://maxiaohu.oss-cn-nanjing.aliyuncs.com/weixin.png
       link:
       text: 微信
     - img: https://maxiaohu.oss-cn-nanjing.aliyuncs.com/zhifubao.png
       link:
       text: 支付宝

